@startuml
autonumber

actor "Coordinator" as COO


activate COO
COO -> ":System" :  starts to import the data
activate ":System"
":System" --> COO : request data (filePath)
deactivate ":System"
COO -> ":System" :  type Requestes data
activate ":System"
":System" --> COO : informs operation success

deactivate ":System"
COO -> ":System" : starts sorting process
activate ":System"
":System" --> COO : Show listSorted
deactivate ":System"


@enduml