@startuml

autonumber
actor "Receptionist" as RCP


participant "lsdui\n:LegacySystemDataUI" as UI
participant "lsdctrl\n:LegacySystemDataCTRL" as CTRL
participant "App" as APP
participant "app\n:App" as App
participant "comp:Company" as COMP
participant "lsdr:LegacySystemDataReader" as LSDR
participant "lsd\n:LegacySystemData" as LSD
participant "snsU: SNSUser" as snsU
participant "svs\n:ScheduleVaccineStore" as SVS
participant "auth\n:AuthFacade" as AF



RCP -> UI : starts to import the data
activate UI
UI -> CTRL : controller = UserArrivalController()
activate CTRL
CTRL -> APP : app = getInstance()
activate APP
deactivate APP
CTRL -> App : company = getCompany()
activate App
deactivate App

deactivate CTRL

UI --> RCP : request data (filePath)
deactivate UI

RCP -> UI : lis
activate UI

UI -> CTRL : newLegacySystemDataReader(filePath)
activate CTRL

CTRL -> LSDR : csvReaderLegacyData(filePath)
activate LSDR


LSDR -> LSDR : createLegacySystemData(attributes)
activate LSDR
deactivate LSDR


UI --> RCP : informs operation success
deactivate LSDR
deactivate CTRL
deactivate UI


RCP -> UI : listLegacyData = getListLegacySystemData()
activate UI

UI -> CTRL : getListLegacySystemData()
activate CTRL
deactivate CTRL

UI --> RCP : returns list with data
deactivate LSDR
deactivate CTRL
deactivate UI



RCP -> UI : getSortChoices()
activate UI

UI -> CTRL : getSortChoices()
activate CTRL


CTRL -> LSD : getSortChoices()
activate LSD
deactivate LSD
deactivate CTRL


UI --> RCP : return Choices

deactivate LSDR
deactivate CTRL
deactivate UI




RCP -> UI : starts sorting process
activate UI

UI -> CTRL : sortByParameters(sortChoice, sortOrder\n, sortArrivalLeaving, listLegacyData)
activate CTRL


CTRL -> LSD : listSorted = sortByParameters(sortChoice,\n sortOrder, sortArrivalLeaving, listLegacyData)
activate LSD
deactivate LSD



CTRL --> UI : return listSorted
deactivate CTRL
UI --> RCP : Show listSorted

deactivate LSDR
deactivate CTRL
deactivate UI
deactivate RCP




@enduml