@startuml

autonumber
actor "Coordinator" as COO


participant "lsdui\n:LegacySystemDataUI" as UI
participant "lsdctrl\n:LegacySystemDataCTRL" as CTRL
participant "App" as APP
participant "oApp\n:App" as App
participant "comp:Company" as COMP
participant "lsdr:LegacySystemDataReader" as LSDR
participant "lsd\n:LegacySystemData" as LSD




COO -> UI : starts to import the data
activate UI
UI -> CTRL : controller = UserArrivalController()
activate CTRL
CTRL -> APP : app = getInstance()
activate APP
deactivate APP
CTRL -> App : company = getCompany()
activate App
deactivate App

deactivate CTRL

UI --> COO : request data (filePath)
deactivate UI

COO -> UI : type Requestes data
activate UI

UI-> CTRL: validateFilePath(filePath)
activate CTRL

CTRL-> LSDR :validateFilePath(filePath)
activate LSDR
deactivate LSDR
UI -> CTRL : newLegacySystemDataReader(filePath)


CTRL -> LSDR : csvReaderLegacyData(filePath)
activate LSDR


LSDR -> LSDR : createLegacySystemData(attributes)
activate LSDR
deactivate LSDR

UI -> CTRL : listLegacyData = getListLegacySystemData()
deactivate LSDR






UI -> CTRL : getSortChoices()



CTRL -> LSD : getSortChoices()
activate LSD
deactivate LSD
deactivate CTRL


UI --> COO : informs operation Success

deactivate LSDR
deactivate CTRL
deactivate UI




COO -> UI : starts sorting process
activate UI

UI -> CTRL : sortByParameters(sortChoice, sortOrder\n, sortArrivalLeaving, listLegacyData)
activate CTRL


CTRL -> LSD : listSorted = sortByParameters(sortChoice,\n sortOrder, sortArrivalLeaving, listLegacyData)
activate LSD
deactivate LSD



CTRL --> UI : return listSorted
deactivate CTRL
UI --> COO : Show listSorted

deactivate LSDR
deactivate CTRL
deactivate UI
deactivate COO




@enduml