@startuml
skinparam classAttributeIconSize 0

class Application {
  +static getInstance()
  +getCurrentSession()
  +getCompany()

}

class EmployeeStore {
-List<Employee> listaEmployee
+createEmployee(name, phoneNumber, address,\nemailAddress, citizenCardNumber, role)
+validateEmployee(emp)
+registerEmployee(emp)
+passwordGenerator(name,email)
+addEmployee(emp)
}

class Employee {
-name
-phoneNumber
-address
-emailAddress
-citizenCardNumber
-companyID
+getEmailAddress()
+getName()
}

class Company {

  +getAuthFacade()
  +getRegisterEmployee()

}



class RegisterEmployeeController {
+getRoles()
+createEmployee(name, phoneNumber, address,\n emailAddress, citizenCardNumber, role)
+registerEmployee()

}

class RegisterEmployeeUI {

}

class AuthFacade{
+getUserRoles()
+existsUser(email)
+addUserWithRole(name, email, pwd, role)
}

RegisterEmployeeUI ..> RegisterEmployeeController
RegisterEmployeeController ..> Employee
RegisterEmployeeController ..> Company
RegisterEmployeeController ..> Application
Application ..> Company
EmployeeStore "1" -> "*" Employee : knows
Company "1" --> "1" EmployeeStore : has

Company ..> AuthFacade

EmployeeStore .left.> AuthFacade


@enduml