@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0


class VaccinatedToFile{
List listVaccinated
List listFullyVaccinated
}

VaccinationCenter "1"-right-"*" VaccinatedToFile : produces >

class VaccinationCenter{
name
phoneNumber
faxNumber
homeAddress
emailAddress
websiteAddress
openingHours
closingHours
slotDuration
maxNumVaccinesPerSlot
}

class CenterCoordinator{
}

CenterCoordinator "1" -up--- "1" VaccinationCenter : coordinates and analyzes >

class Company{
designation
}

Company "1" -up-- "*" VaccinationCenter : manages >


@enduml