@startuml
autonumber

actor "Coordinator" as COO

participant ":VaccinatedToFileUI" as UI
participant ":VaccinatedToFileController" as CTRL
participant "App" as APP
participant "oApp\n:App" as oApp
participant "comp:Company" as COMP
participant "vcs\n:VaccinationCenter" as VC
participant "vtf\n:VaccinatedToFile" as VTF

activate COO
COO -> UI : asks to export fully vaccinated users to file
activate UI
UI -> CTRL : controller = VaccinatedToFileController()
activate CTRL
CTRL -> APP : app = getInstance()
activate APP
deactivate APP
CTRL -> oApp : company = getCompany()
activate oApp
deactivate oApp

deactivate CTRL

UI --> COO : requests data (fileName)
deactivate UI

COO -> UI : types requested data
activate UI

UI -> CTRL : validateFileName(fileName)
activate CTRL

CTRL -> COMP : validateFileName(fileName)
activate COMP

COMP -> VTF : validateFileName(fileName)
activate VTF
deactivate VTF
deactivate COMP

deactivate CTRL

UI --> COO : informs operation success

deactivate UI

COO -> UI : asks to export to file
activate UI

UI -> CTRL : writeToFile(String fileName)
activate CTRL

CTRL -> COMP : writeToFile(String fileName)
activate COMP

COMP -> VTF : writeToFile(String fileName)
activate VTF

VTF -> VTF : getListVaccinated()
activate VTF
deactivate VTF
VTF -> VTF : getFullyVaccinatedPatients()
activate VTF
deactivate VTF

deactivate VTF
deactivate VTF
deactivate COMP


UI --> COO : shows fully vaccinated users
deactivate CTRL
deactivate UI

deactivate COO

@enduml