@startuml
autonumber
actor "Coordinator" as COO

activate COO
COO -> ":System" : asks to export fully vaccinated users to file
activate ":System"
":System" --> COO : requests data (fileName)
deactivate ":System"

COO -> ":System" : types requested data
activate ":System"
":System" --> COO : informs operation success
deactivate ":System"

COO -> ":System" : asks to export to file
activate ":System"
":System" --> COO : shows fully vaccinated users
deactivate ":System"



deactivate COO

@enduml