@startuml
autonumber
'hide footbox
actor "Administrator" as ADM

participant ":RegisterVaccinationCenterUI" as UI
participant ":RegisterVaccinationCenterController" as CTRL
participant "App" as _APP
participant "app\n:App" as APP
participant "comp\n:Company" as COMP
participant ":RegisterVaccinationCenter" as RVC
participant "center\n:VaccinationCenter" as VC
participant "lvct\n:List<String> vaccinationCenterTypes" as LVCT

activate ADM
ADM -> UI : starts the registration of a new vaccination center
activate UI
UI -> CTRL : getVaccinationCenterTypes()
activate CTRL
CTRL -> _APP : app = getInstance()
activate _APP
deactivate _APP
CTRL -> APP : comp = getCompany()
activate APP
deactivate APP
CTRL -> COMP : lvct = getVaccinationCenterTypes()
activate COMP
deactivate COMP
deactivate CTRL
UI --> ADM : shows different types of vaccination centers \nand asks user to select one
deactivate UI
|||


ADM -> UI : selects the desired type of vaccination center
activate UI
|||
UI --> ADM : requests data (name, phoneNumber, faxNumber,\nhomeAddress, emailAddress, websiteAddress,\nopeningHours, closingHours, slotDuration,\nmaxNumVaccinesPerSlot)
deactivate UI
|||

ADM -> UI : types requested data
activate UI
UI -> CTRL : createCenter(vaccinationCenterType, name,\nphoneNumber, faxNumber,homeAddress, emailAddress,\nwebsiteAddress,openingHours, closingHours, slotDuration,\nmaxNumVaccinesPerSlot)
activate CTRL
CTRL -> COMP : rvc = getRegisterVaccinationCenter()
activate COMP
deactivate COMP
CTRL -> RVC : center = createAndSaveCenter(vaccinationCenterType, name,\nphoneNumber, faxNumber,homeAddress, emailAddress,\nwebsiteAddress, openingHours, closingHours, slotDuration,\nmaxNumVaccinesPerSlot)
activate RVC
RVC -> VC ** : create(vaccinationCenterType, name,\nphoneNumber, faxNumber,homeAddress, emailAddress,\nwebsiteAddress, openingHours, closingHours, slotDuration,\nmaxNumVaccinesPerSlot)
RVC -> RVC : validateCenter(center)
deactivate CTRL
UI --> ADM: shows all data and requests confirmation
deactivate RVC

deactivate CTRL
deactivate UI

ADM -> UI : confirms the data
activate UI
UI -> CTRL : saveCenter()
activate CTRL
|||
CTRL -> RVC : saveCenter(center)
activate RVC
RVC -> VC ** : saveCenter(center)
RVC -> RVC : validateCenter(center)
RVC -> RVC : addCenter(center)
UI --> ADM : informs operation success
CTRL --> UI : result
deactivate RVC
deactivate CTRL
deactivate UI
@enduml