@startuml
skinparam classAttributeIconSize 0


class AuthFacade{
+getUserRoles()
+existsUser(email)
}

class Application {
  +static getInstance()
  +getCurrentSession()
  +getCompany()

}

class Company {
+getplatform()
+getAuthFacade()
+getRegisterEmployee()
}

class Employee {
-name
-phoneNumber
-address
-emailAddress
-citizenCardNumber
-companyID
+getEmailAddress()
+getName()
}


class RegisterEmployee{
+getListEmployees()

}






class ListEmployeesController {
+getRoles()
  +getListEmployees()
  +listEmployeesByRole(role)


}

class ListEmployeesUI {

}

ListEmployeesUI ..> ListEmployeesController
ListEmployeesController ..> Application
ListEmployeesController ..> Company
Company ..> AuthFacade
RegisterEmployee .left.> AuthFacade
ListEmployeesController ..> Employee
Company "1" --> "1" RegisterEmployee : has
RegisterEmployee -right-> Employee : knows





@enduml