@startuml
skinparam classAttributeIconSize 0






class Employee {
+listEmployees(function)
}



class AuthVerification{
+verifyAuthorization
}


class ListEmployeesController {
  +getListEmployees(function)

}

class ListEmployeesUI {
+askFunction()
}

ListEmployeesUI ..> ListEmployeesController
ListEmployeesController ..> Platform
Platform ..> Employee
Employee <|--- Nurse
Employee <|--- Receptionist
Employee <|--- CenterCoordinator
ListEmployeesUI ..> AuthVerification



@enduml