@startuml
autonumber
actor "Administrator" as ADM

activate ADM
ADM -> ":System" : asks to return list of Employees
activate ":System"
":System" --> ADM : ask to select employee role
deactivate ":System"

ADM -> ":System" : selects requested role
activate ":System"
":System" --> ADM : shows required list
deactivate ":System"




deactivate ADM

@enduml