@startuml
autonumber
actor "Administrator" as ADM

activate ADM
ADM -> ":System" : asks to return list of Employees
activate ":System"
":System" --> ADM : requests specific function/role
deactivate ":System"

ADM -> ":System" : types requested function/role
activate ":System"
":System" --> ADM : shows required list
deactivate ":System"




deactivate ADM

@enduml