@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Receptionist" as RCP

activate RCP
RCP -> ":System" : starts registering the arrival of the user
activate ":System"
":System" --> RCP : request data (name, snsUserNumber, \ncitizenCardNumber, vaccineScheduleDate)
deactivate ":System"

RCP -> ":System" : types requested data
activate ":System"
":System" --> RCP : shows the data and requests a confirmation
deactivate ":System"

RCP -> ":System" : confirms the data
activate ":System"
":System" --> RCP : informs operation success
deactivate ":System"
@enduml