@startuml
'https://plantuml.com/class-diagram

class Nurse{}


class Employee{
name
phoneNumber
address
emailAddress
citizenCardNumber
companyID
}




class WaitingRoom{}


Nurse--|>Employee
Nurse "*" -right- "1..*" WaitingRoom : Consults Users in Waiting Rooom
@enduml