@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Nurse" as Nurse

activate Nurse
Nurse -> ":System" : wants to schedule a vaccine
activate ":System"
":System" --> Nurse : requests SNS user number
deactivate ":System"

Nurse -> ":System" : types SNS user number
activate ":System"
":System" --> Nurse : asks to select the vaccination center, date and time
deactivate ":System"



deactivate Nurse
@enduml