@startuml
autonumber
'hide footbox
actor "Administrator" as ADM

participant ":ListWaitingRoomUI" as UI
participant ":ListWaitingRoomController" as CTRL
participant "App" as _APP
participant "app\n:App" as APP
participant "comp\n:Company" as COMP
participant ":UserArrivalStore" as UA
participant ":Utils" as U
participant "user\n:SNSUser" as SU



activate ADM
ADM -> UI : requests list of people in the waiting room
activate UI
UI -> CTRL : getUsersWaitingRoom()
activate CTRL
CTRL -> _APP : app = getInstance()
activate _APP
deactivate _APP
CTRL -> APP : comp = getCompany()
activate APP
deactivate APP
CTRL -> COMP : getWaitingRoom()
activate COMP
deactivate COMP
CTRL -> UA : getListUsersInWaitingRoom()
activate UA
deactivate UA
deactivate CTRL
UI -> U : ShowList(List list, String header)
activate U
deactivate U

UI --> ADM : Shows the requested list
deactivate UI
deactivate ADM





@enduml