@startuml
'https://plantuml.com/class-diagram
class ListWaitingRoomUI
class ListWaitingRoomController{
+getUsersWaitingRoom()
}
class Company{
+getWaitingRoom()
}
class WaitingRoom{
+listUsersWaitingRoom()
}
class Application{
+getInstance()
+getCompany()
}



@enduml