@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Nurse" as Nurse

activate Nurse
Nurse -> ":System" : Requests list of people in the waiting room
activate ":System"
":System" --> Nurse : Shows the requested list
deactivate ":System"





deactivate Nurse
@enduml