@startuml
'https://plantuml.com/sequence-diagram

autonumber

Receptionist -> Bob: Authentication Request
Bob --> Receptionist: Authentication Response

Receptionist -> Bob: Another authentication Request
Receptionist <-- Bob: another authentication Response
@enduml