@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

class App{
    +getCompany()
    +static getInstance()
}

class SNSUser{
    -String name
    -String phoneNumber
    -String faxNumber
    -String homeAddress
    -String emailAddress
    -String websiteAddress
    -Double openingHours
    -Double closingHours
    -Double slotDuration
    -Integer maxNumVaccinesPerSlot
    +SNSUser(name, address, gender, phoneNumber, birthDate,\nemailAddress, snsUserNumber,citizenCardNumber)

}


class LoadSNSUserUI {
}


class LoadSNSUserController{
    +getCsvFileTypes()
    +csvToArray(fileType, fileName, fileLocation)
    +loadUsers()
    +saveUsers()
}

class Company {
    -designation
    +getRegisterVaccinationCenter()
}

class CSVFileReader{
    +getCsvFileTypes()
    +csvToArray(fileType, fileName, fileLocation)
    -validateArray(array)
}

class loadSNSUser{
    +createUser(name, address, gender, phoneNumber, birthDate,\nemailAddress, snsUserNumber,citizenCardNumber)
    +saveUser(SNSUser user)
    -validateUser(SNSUser user)
    -addUser(SNSUser user)
}

LoadSNSUserUI .down.> LoadSNSUserController
LoadSNSUserController .down.> Company
Company "1" -down- "1" loadSNSUser : has >
Company "1" -down- "1" CSVFileReader : has >
loadSNSUser "1" -up- "*" SNSUser : has >
LoadSNSUserController ..> SNSUser
LoadSNSUserController ..> App


@enduml