@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "SNS User" as User

activate User
User -> ":System" : wants to schedule a vaccine
activate ":System"
":System" --> User : shows and asks to select the vaccination center and the vaccine type
deactivate ":System"

User -> ":System" : selects vaccination center and vaccine type
activate ":System"
":System" --> User : asks to introduce date and time
deactivate ":System"

User -> ":System" : introduces date and time
activate ":System"
":System" --> User : shows all data and requests confirmation
deactivate ":System"

User-> ":System" : confirms the data
activate ":System"
":System" --> User : infoms operation (in)sucess
deactivate ":System"
deactivate User

@enduml