@startuml
'https://plantuml.com/sequence-diagram

class ScheduleVaccineController{
+getVaccinationCenter()
+getVaccineTypes()
+newScheduleVaccine(snsUserNumber, vaccinationCenter, dateTime, vaccineType)
}

class ScheduleVaccineUI{

}

class ScheduleVaccine{
+snsUserNumber
+ vaccinationCenter
+dateTime
+vaccineType
+create(snsUserNumber, vaccinationCenter, dateTime, vaccineType)
}

class Company{
-designation
+getVaccinationCenter()
+getVaccineTypes()
+getScheduleVaccineStore()
+listScheduleVaccine()
}

class ScheduleVaccineStore{
+newScheduleVaccine(snsUserNumber, vaccinationCenter, dateTime, vaccineType)
+registerScheduleVaccine(scheduleVaccine)
+validateScheduleVaccine(scheduleVaccine)
+existsScheduleVaccine(scheduleVaccine)
+addScheduleVaccine(scheduleVaccine)
}

class App{
+getInstance()
+getCompany()
}

ScheduleVaccineUI .down.> ScheduleVaccineController
ScheduleVaccineController .down.> Company
ScheduleVaccineController .> ScheduleVaccine
ScheduleVaccineController .>App
Company .down.> ScheduleVaccineStore
ScheduleVaccineStore .> ScheduleVaccine
@enduml