@startuml
'https://plantuml.com/sequence-diagram

autonumber
'hide footbox
actor "SNS User" as USER

participant ":ScheduleVaccineUI" as UI
participant ":ScheduleVaccineController" as CTRL
participant "App" as _APP
participant "app\n:App" as APP
participant "comp\n:Company" as COMP
participant ":ScheduleVaccineStore" as STORE
participant "SV\n: ScheduleVaccine" as SV
participant "LSV\n:List<String> listScheduleVaccine" as LSV

activate USER
USER -> UI : wants to schedule a vaccine
activate CTRL
activate UI
UI -> CTRL : getVaccinationCenter()
CTRL -> _APP : app = getInstance()
activate _APP
deactivate _APP
CTRL -> APP : comp = getCompany()
activate APP
deactivate APP
CTRL -> COMP : lvc = getVaccinationCenter()
activate COMP
deactivate COMP
UI -> CTRL : getVaccineTypes()
CTRL -> COMP : lvt = getVaccineTypes()
activate COMP
deactivate COMP
deactivate CTRL
UI --> USER : shows and asks to select the vaccination center and the vaccine type
deactivate UI
|||


USER -> UI : selects vaccination center and vaccine type
activate UI
|||
UI --> USER : asks to introduce date and time
deactivate UI
|||



USER -> UI : introduces date and time
activate UI
|||
UI --> USER: shows all data and requests confirmation
deactivate UI
|||


USER -> UI : confirms the data
activate UI
UI -> CTRL : newScheduleVaccine(snsUserNumber,vaccination center, dateTime, vaccineType)
activate CTRL
CTRL -> COMP : store = getScheduleVaccineStore()
activate COMP
deactivate COMP
CTRL -> COMP : lsv = listScheduleVaccine()
activate COMP
deactivate COMP
CTRL -> STORE : scheduleVaccine = newScheduleVaccine(snsUserNumber, \n vaccinationCenter, dateTime, vaccineType)
activate STORE
STORE -> SV ** : create (snsUserNumber, vaccinationCenter, dateTime, vaccineType)
deactivate STORE
CTRL -> STORE : registerScheduleVaccine(scheduleVaccine)
activate STORE
STORE -> STORE : validateScheduleVaccine(scheduleVaccine)
activate STORE
deactivate STORE
STORE -> STORE : existsScheduleVaccine(scheduleVaccine)
activate STORE
deactivate STORE
STORE -> STORE : addScheduleVaccine(scheduleVaccine)
activate STORE
deactivate STORE
deactivate STORE
CTRL --> UI : result
UI --> USER : informs operation (in)success

deactivate CTRL
deactivate UI
@enduml