@startuml
'https://plantuml.com/sequence-diagram

autonumber
'hide footbox
actor "SNS User" as USER

participant ":ScheduleVaccineUI" as UI
participant ":ScheduleVaccineController" as CTRL
participant "App" as _APP
participant "app\n:App" as APP
participant "comp\n:Company" as COMP
participant ":ScheduleVaccineStore" as STORE
participant "SV\n: ScheduleVaccine" as SV
participant "LVA\n:List<String> listVaccineAppointments" as LVA

activate USER
USER -> UI : wants to schedule a vaccine
activate UI
|||
UI --> USER : requests SNS user number
deactivate UI
|||


USER -> UI : types SNS user number
activate UI
UI -> CTRL : getListVaccinationCenter()
activate CTRL
CTRL -> _APP : app = getInstance()
activate _APP
deactivate _APP
CTRL -> APP : comp = getCompany()
activate APP
deactivate APP
CTRL -> COMP : lvc = getListVaccinationCenter()
activate COMP
deactivate COMP
CTRL -> COMP : store = getScheduleVaccineStore()
activate COMP
deactivate COMP
UI -> CTRL : getAvailableDate()
CTRL -> STORE : gad = getAvailableDate()
activate STORE
deactivate STORE
UI -> CTRL : getAvailableTime()
CTRL -> STORE : gat = getAvailableTime()
activate STORE
deactivate STORE
deactivate CTRL
UI --> USER : shows and asks to select the vaccination center, date and time
deactivate UI
|||



USER -> UI : chooses vaccination center, date and time
activate UI
|||
UI --> USER: shows all data and requests confirmation
deactivate UI
|||


USER -> UI : confirms the data
activate UI
UI -> CTRL : createAppointment(SNS User number,vaccination center, date, time)
activate CTRL
CTRL -> COMP : VA = getAppointments()
activate COMP
deactivate COMP
CTRL -> STORE : appointment = createAppointment(SNSUserNumber, \n vaccinationCenter, date, time)
activate STORE
STORE -> SV ** : create (SNSUserNumber, vaccinationCenter, date, time)
deactivate STORE
CTRL -> STORE : saveAppointment(appointment)
activate STORE
STORE -> STORE : validateAppointment(appointment)
activate STORE
deactivate STORE
STORE -> STORE : addAppointment(appointment)
activate STORE
deactivate STORE
deactivate STORE
CTRL --> UI : result
UI --> USER : informs operation (in)success

deactivate CTRL
deactivate UI
@enduml