@startuml
autonumber
actor "Nurse" as NU
participant "VaccineAdministrationUI" as UI
participant "VaccineAdministrationController" as CTRL
participant "App" as _APP
participant "app\n:App" as APP
participant "comp\n:Company" as COMP
participant "empStore\n:EmployeeStore" as EMPSTORE
participant "VaccinationCenter" as VC
participant "UserArrival" as UA
participant "VaccineSchedule" as VS
participant "VaccineAdministration" as VA
participant "wr\n:List <UserArrival> waitingRoom"
participant "rr\n:List <VaccineAdministration> recoveryRoom"



activate NU
NU -> UI : asks to record the administration of a vaccine
activate UI
UI -> CTRL : getWorking()
activate CTRL
CTRL -> _APP : app = getInstance()
activate _APP
deactivate _APP
CTRL -> APP : comp = getCompany()
activate APP
deactivate APP
CTRL -> COMP : empStore = getEmployeeStore()
activate COMP
deactivate COMP
CTRL -> EMPSTORE : working = getWorking()
activate EMPSTORE
deactivate EMPSTORE
deactivate CTRL
deactivate CTRL



UI --> NU : shows data (user, vaccine) and asks to select one
deactivate UI

NU -> UI : selects desired data
activate UI
UI -> CTRL : getWaitingRoom()
activate CTRL
CTRL -> VC  : user = getListUserToWaitingRoom()
activate VC
deactivate VC
deactivate CTRL
UI -> CTRL : getAvailableVaccinesForUser(user)
activate CTRL
CTRL -> UA : schedule = getSchedule()
activate UA
deactivate UA
CTRL -> VS : getVaccineList()
activate VS
deactivate VS
deactivate CTRL
UI -> CTRL : validateVaccineAdministration(user, vaccine)
activate CTRL
CTRL -> VC : administration =  validateVaccineAdministration(user,vaccine)
activate VC
VC -> VC : getVaccineAdministration()
loop
VC -> VC : validateVaccineAdministration(user,vaccine)
VC -> VA : setVaccinationTime(date)
activate VA
deactivate VA
end
deactivate VC
CTRL -> VA : date = getDate()
activate VA
deactivate VA
deactivate CTRL
deactivate UA
alt if administration == null
UI -> CTRL : createVaccineAdministration(user, vaccine, date)
activate CTRL
    CTRL -> VC : createVaccineAdministration(user, vaccine, date)
    activate VC
    VC -> VA : create(user, vaccine, date)
    activate VA
    deactivate VA
    VC -> VC : saveAdministration()
    activate VC
    deactivate VC
    deactivate VC
end
deactivate CTRL


UI --> NU : shows all data and requests confirmation
deactivate UI

NU -> UI : confirms the data

activate UI
UI->CTRL : addVaccineAdministration(administration)
activate CTRL
CTRL->VC : addVaccineAdministration(administration)
activate VC


deactivate VC


deactivate CTRL
UI->CTRL : removeFromWaitingRoom(user)
activate CTRL
CTRL->VC : removeFromWaitingRoom(user)
activate VC


deactivate VC

deactivate CTRL
UI->CTRL : moveToRecoveryRoom(administration, vaccine)
activate CTRL
CTRL->VC : moveToRecoveryRoom(administration)
activate VC
deactivate VC


deactivate CTRL


UI --> NU : informs operation success
deactivate UI

deactivate NU
@enduml