@startuml
autonumber
actor "Nurse" as NU

activate NU
NU -> ":System" : Asks to record the administration of a vaccine
activate ":System"
":System" --> NU : Asks to select the SNS user from the waiting room
deactivate ":System"

NU -> ":System" : Selects the SNS user from the waiting room
activate ":System"
":System" --> NU : Shows and asks to select available(s) vaccine for chosen user
deactivate ":System"

NU -> ":System" : Selects the vaccine
activate ":System"
":System" --> NU : Asks if the Nurse wants to record the administration
deactivate ":System"

NU -> ":System" : Confirms
activate ":System"
":System" --> NU : Informs operation success
deactivate ":System"

deactivate NU
@enduml