@startuml
autonumber
actor "Nurse" as NU

activate NU
NU -> ":System" : asks to record the administration of a vaccine
activate ":System"
":System" --> NU : shows data (user, vaccine) and asks to select one
deactivate ":System"

NU -> ":System" : selects desired data
activate ":System"
":System" --> NU : shows all data and requests confirmation
deactivate ":System"

NU -> ":System" : confirms the data
activate ":System"
":System" --> NU : informs operation success
deactivate ":System"

deactivate NU
@enduml